Mess/urls.py
from django.conf.urls import include,url
from . import views

urlpatterns = [
    url(r'^$',views.homepage,name='homepage'),
	url(r'^messmenu',views.messmenu,name='messmenu'),
    url(r'^refund/$', views.refund, name='refund'),
    url(r'^feedback/$', views.feedback, name='feedback'), 
    url('^login/(?P<token>.+)$',views.login,name="login"),
    url('^login_user$',views.login_user,name="login_user")
]

hostelandmess/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^hostel/', include('Hostel.urls')),
	url(r'^mess/', include('Mess.urls')),
	url(r'^', include('Mess.urls'))
]

Mess/models.py
from __future__ import unicode_literals
from django.db import models
from datetime import datetime
from Hostel.models import Student
class MessFeedback(models.Model):
	student= models.ForeignKey(Student,on_delete=models.CASCADE,default=None)
	time = models.DateTimeField(default=datetime.now())
	feedback = models.CharField(max_length=200)
	def __str__(self):
		return str(str(self.feedback) +","+str(self.time))
class Refund(models.Model):
	student= models.ForeignKey(Student,on_delete=models.CASCADE,default=None)
	to_date=models.DateField(default=None)
	from_date=models.DateField(default=None)
	mail_proof=models.FileField(default=None)
	def __str__(self):
		return str(self.outdate+","+self.indate)
class BankDetails(models.Model):
	student   = models.ForeignKey(Student,on_delete=models.CASCADE,default=None)
	bank_name =models.CharField(max_length=250)
	ifsc      =models.CharField(max_length=250)
        branchname =models.CharField(max_length=250)
	acholdername=models.CharField(max_length=250)

Mess/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Refund,MessFeedback


class RefundForm(forms.ModelForm):

    class Meta:
        model = Refund
        fields = ['from_date', 'to_date', 'mail_proof']
class FeedbackForm(forms.ModelForm):

    class Meta:
        model = MessFeedback
        fields = ['feedback']

Mess/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse,HttpResponse
from django.shortcuts import render, get_object_or_404
from .forms import RefundForm,FeedbackForm
from django.contrib.auth import get_user_model
from Hostel.models  import Student
from Mess.models import Refund
User = get_user_model()

IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg','pdf']

def homepage(request):
	return render(request,'Mess/MyHome.html')
def messmenu(request):
	return render(request,'Mess/messmenu.html')
def refund(request):
    if not request.user.is_authenticated():
        return render(request, 'Mess/login.html')
    else:
        form = RefundForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            mess = form.save(commit=False)
            #mess.student = Student.objects.get(user=request.user)
	    usr=User.objects.get(username=request.user.username)
	    stud=Student()
	    stud=Student.objects.get(user=usr)
			
			

        		
            			
            from_date=request.POST.get('from_date')
	    to_date=request.POST.get('to_date')
				
	    messrefund=Refund()
	    messrefund.from_date=from_date
	    messrefund.mail_proof=request.FILES.get('mail_proof')
	    messrefund.to_date=to_date
	    messrefund.student=stud
           
            #mess.mail_proof = request.FILES['mail_proof']
            file_type = mess.mail_proof.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    #'mess': mess,
                    #'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'Mess/refund.html', context)
            messrefund.save()
            return render(request, 'Mess/popup.html', {'error_message': 'refund form submitted successfully'})
        context = {
            "form": form,
        }
        return render(request, 'Mess/refund.html', context)


def feedback(request):
    if not request.user.is_authenticated():
        return render(request, 'Mess/login.html')
    else:
        form = FeedbackForm(request.POST or None)
        if form.is_valid():
            mess = form.save(commit=False)
            mess.student = Student.objects.get(user=request.user)
            mess.save()
            return render(request, 'Mess/popup.html', {'error_message': 'feedback submitted successfully'})
        context = {
            "form": form
        }
        return render(request, 'Mess/feedback.html', context)

import json
import requests
from django.shortcuts import get_object_or_404, render

def login(request,token):
    print ('hello')
    res = requests.post(url='https://serene-wildwood-35121.herokuapp.com/oauth/getDetails', data={
    'token': token,
    'secret': 'ff5bbfae032e66f2abdb15b113bfab5d3f1741b1ed1f60b04e7062d74024bad29f57b82e6cfe0eee53ee6e595405c00907af0179c85c2c0c396e6e3df1f250a7'
})
    res = json.loads(res.content)
    email = res['student'][0]['Student_Email']
    print(email)
    if(email):
        return render(request,'Mess/loginsuccess.html',{'email':email})

def login_user(request):
        return render(request,'Mess/login.html')

Mess/templates/Mess/MessRefund.html
<!DOCTYPE html>
<html>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<head>
<style>
.card {
    box-shadow: 0 10px 15px 0 rgba(0,0,0,0.2);
    transition: 0.3s;
    width: 130%;
	padding: 5px 5px;
	border-radius: 40px;
}

.card:hover {
    box-shadow: 0 40px 35px 0 rgba(0,0,0,0.2);
}


.button {
  display: inline-block;
  border-radius: 0px;
  background-color: #007bff;
  border: none;
  color: #FFFFFF;
  text-align: center;
  font-size: 22px;
  padding: 15px;
  width: 220px;
  transition: all 0.5s;
  cursor: pointer;
  margin: 0px;
}

.button span {
  cursor: pointer;
  display: inline-block;
  position: relative;
  transition: 0.5s;
}

.button span:after {
  content: '\2193';
  position: absolute;
  opacity: 0;
  top: 0;
  right: -20px;
  transition: 0.5s;
}

.button:hover span {
  padding-right: 30px;
}

.button:hover span:after {
  opacity: 1;
  right: 0;
}

/* Style The Dropdown Button */
.dropbtn {
    background-color: #4CAF50;
    color: white;
    padding: 16px;
    font-size: 16px;
    border: none;
    cursor: pointer;
}

/* The container <div> - needed to position the dropdown content */
.dropdown {
    position: relative;
    display: inline-block;
}

/* Dropdown Content (Hidden by Default) */
.dropdown-content {
    display: none;
    position: absolute;
    background-color: #f9f9f9;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
}

/* Links inside the dropdown */
.dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
}

/* Change color of dropdown links on hover */
.dropdown-content a:hover {background-color: #f1f1f1}

/* Show the dropdown menu on hover */
.dropdown:hover .dropdown-content {
    display: block;
}

/* Change the background color of the dropdown button when the dropdown content is shown */
.dropdown:hover .dropbtn {
    background-color: #3e8e41;
}

* {box-sizing: border-box;}
body {font-family: Verdana, sans-serif;}
.mySlides {display: none;}
img {vertical-align: middle;}

/* Slideshow container */
.slideshow-container {
  max-width: 750px;
  position: relative;
  margin: auto;
}

/* Caption text */
/*.text {
  color: #f2f2f2;
  font-size: 15px;
  padding: 8px 12px;
  position: absolute;
  bottom: 8px;
  width: 100%;
  text-align: center;
}*/

/* Number text (1/3 etc) */
/*.numbertext {
  color: #f2f2f2;
  font-size: 12px;
  padding: 8px 12px;
  position: absolute;
  top: 0;
}

/* The dots/bullets/indicators */
.dot {
  height: 15px;
  width: 15px;
  margin: 0 2px;
  background-color: #bbb;
  border-radius: 50%;
  display: inline-block;
  transition: background-color 0.6s ease;
}

.active {
  background-color: #717171;
}

/* Fading animation */
.fade {
  -webkit-animation-name: fade;
  -webkit-animation-duration: 1.5s;
  animation-name: fade;
  animation-duration: 1.5s;
}

@-webkit-keyframes fade {
  from {opacity: .4} 
  to {opacity: 1}
}

@keyframes fade {
  from {opacity: .4} 
  to {opacity: 1}
}

/* On smaller screens, decrease text size */
@media only screen and (max-width: 300px) {
  .text {font-size: 11px}
}


select {
  margin: 50px;
  width: 150px;
  padding: 5px 35px 5px 5px;
  font-size: 16px;
  border: 1px solid #ccc;
  height: 34px;
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
}

/* CAUTION: IE hackery ahead */
select::-ms-expand { 
    display: none; /* remove default arrow on ie10 and ie11 */
}

/* target Internet Explorer 9 to undo the custom arrow */
@media screen and (min-width:0\0) {
    select {
        background:none\9;
        padding: 5px\9;
    } 
}
form button {
  margin-top: 35px;
  background-color: white;
  border: 1px solid #B22222;
  line-height: 0;
  font-size: 17px;
  display: inline-block;
  box-sizing: border-box;
  padding: 20px 15px;
  border-radius: 60px;
  color: #B22222;
  font-weight: 100;
  letter-spacing: 0.01em;
  position: relative;
  z-index: 1;
}
form button:hover, form button:focus {
  color: white;
  background-color: #ff4a56;
}
textarea {
    width: 100%;
    height: 150px;
    padding: 12px 20px;
    box-sizing: border-box;
    border: 2px solid ##6f4f4f;
    border-radius: 4px;
    background-color: #f8f8f8;
    font-size: 16px;
    resize: none;
}
</style>

</head>
<body>
<script>
function as(){
 var my_time = new Date()
      alert("query submitted successfully at " + my_time);
    }
</script>

	<table align="center" width="100%" bgcolor="#343a40">
		<tr>
			<th>
				<div style="background-color:#343a40;width:100%;" align="right"><div style="width:10%;"><img src="iiit.png" height="100" width="100" alt="no image"></div>
			</th>
			<th>
				<p><font color="#ffffff" size="5">Indian institute of Information Technology , Sri city , Chittoor</font></p><font color="#ffffff" size=4>(An Institute of National Importance under Act of Parliament)</p></font>
			</th>
		</tr>
	</table><center>
<div style="background-color:#007bff" >
  <div class="dropdown">
    <button class="button" style="vertical-align:middle" onclick="window.location.href='file:///C:/Users/dell/Desktop/ASE-WEBPAGE/MyHome.html#'" >
      <span>HOME </span></button>
  </div>
  <div class="dropdown">
    <button class="button" style="vertical-align:middle">
      <span>HOSTEL </span></button>
      <div class="dropdown-content">
        <a href="roomregistration.html">ROOM REGISTRATION</a>
        <a href="HostelLeave.html">HOSTEL LEAVE</a>
        <a href="hostelComplaints.html">HOSTEL COMPLAINT</a>
        <a href="Guest entry.html">GUESTS ENTRY</a>
      </div>
  </div>
  <div class="dropdown">
    <button class="button" style="vertical-align:middle">
      <span>MESS </span></button>
      <div class="dropdown-content">
        <a href="messmenu.html">MESS MENU</a>
        <a href="messfeedback.html">MESS COMPLAINT</a>
        <a href="MessRefund.html">MESS REFUND</a>
      </div>
   </div>
	<button class="button" style="vertical-align:middle" onclick="window.location.href='file:///C:/Users/dell/Desktop/ASE-WEBPAGE/Login.html#'"><span>LOGOUT </span></button></center>
</div>
</center>	
<br>
<table>
<tr >
  <td width="30%">
<div class="img-rounded" style="float: left; background-color: #ffc107; width: 300px; height: 500px; border: 1px solid black; margin: 10px;"><h3 style="color: #ffffff; background-color: #28a745; text-align: center; margin: 0px; padding: 0px;">Announcements</h3><div id="cc-homepage-announcements" style="height: 320px; overflow-x: hidden; overflow-y: auto; padding: 6px; text-align: left;">&nbsp;</div>
</div>
  </td>
  
  <td width="63.5%" valign="top" >
	<center><h1 class="card" style="color:#B22222;font-size:41px;font-family:Copperplate Gothic Bold">MESS REFUND</h1></center>

	&emsp;&emsp;&emsp;
	<div class="card">
		<form role="form" action="" method="post" enctype="multipart/form-data" onSubmit="as()">
                        {% csrf_token %}
		<div class="question">
			<fieldset>
			<center>
			<p>From-Date:<input type="date" name="from_date"></p>
			</center>
			</fieldset>
			<fieldset>
			<center>
			<p align="center">To-Date:<input type="date" name="to_date"></p><br>
			</center>
			</fieldset>
			
	<p style="color:#B22222;font-size:20px;font-family:Copperplate Gothic Bold" align="center">Upload you proof here</p>
    <center><fieldset><input type="file" name="mail_proof" accept="pdf/*"></fieldset></center>
	<center><button type="submit">SUBMIT</button></center></div></form>
	</div>
</td>
</tr>
</table>
</body>
</html>

Mess/templates/Mess/feedback.html
{% load static %}
<!DOCTYPE html>
<html>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<head>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/w3.css" >
<style>
.card {
    box-shadow: 0 10px 15px 0 rgba(0,0,0,0.2);
    transition: 0.3s;
    width: 130%;
  padding: 5px 5px;
  border-radius: 40px;
}

.card:hover {
    box-shadow: 0 40px 35px 0 rgba(0,0,0,0.2);
}
.button {
  display: inline-block;
  border-radius: 0px;
  background-color: #007bff;
  border: none;
  color: #FFFFFF;
  text-align: center;
  font-size: 22px;
  padding: 15px;
  width: 220px;
  transition: all 0.5s;
  cursor: pointer;
  margin: 0px;
}

.button span {
  cursor: pointer;
  display: inline-block;
  position: relative;
  transition: 0.5s;
}

.button span:after {
  content: '\2193';
  position: absolute;
  opacity: 0;
  top: 0;
  right: -20px;
  transition: 0.5s;
}

.button:hover span {
  padding-right: 30px;
}

.button:hover span:after {
  opacity: 1;
  right: 0;
}

/* Style The Dropdown Button */
.dropbtn {
    background-color: #4CAF50;
    color: white;
    padding: 16px;
    font-size: 16px;
    border: none;
    cursor: pointer;
}

/* The container <div> - needed to position the dropdown content */
.dropdown {
    position: relative;
    display: inline-block;
}

/* Dropdown Content (Hidden by Default) */
.dropdown-content {
    display: none;
    position: absolute;
    background-color: #f9f9f9;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
}

/* Links inside the dropdown */
.dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
}

/* Change color of dropdown links on hover */
.dropdown-content a:hover {background-color: #f1f1f1}

/* Show the dropdown menu on hover */
.dropdown:hover .dropdown-content {
    display: block;
}

/* Change the background color of the dropdown button when the dropdown content is shown */
.dropdown:hover .dropbtn {
    background-color: #3e8e41;
}


form {
  position: relative;
  display: inline-block;
  max-width: 700px;
  min-width: 500px;
  box-sizing: border-box;
  padding: 30px 25px;
  background-color: white;
  border-radius: 40px;
  margin: 40px 0;
  left: 50%;
  -moz-transform: translate(-50%, 0);
  -ms-transform: translate(-50%, 0);
  -webkit-transform: translate(-50%, 0);
  transform: translate(-50%, 0);
}
form h1 {
  color: #6f4f4f;
  font-weight: 100;
  letter-spacing: 0.01em;
  margin-left: 0px;
  margin-bottom: 0px;
  text-transform: uppercase;
}
form button {
  margin-top: 35px;
  background-color: white;
  border: 1px solid #B22222;
  line-height: 0;
  font-size: 17px;
  display: inline-block;
  box-sizing: border-box;
  padding: 20px 15px;
  border-radius: 60px;
  color: #B22222;
  font-weight: 100;
  letter-spacing: 0.01em;
  position: relative;
  z-index: 1;
}
form button:hover, form button:focus {
  color: white;
  background-color: #ff4a56;
}
form .question {
  position: relative;
  padding: 10px 0;
}
form .question:first-of-type {
  padding-top: 0;
}
form .question:last-of-type {
  padding-bottom: 0;
}
form .question label {
  transform-origin: left center;
  color: #6f4f4f;
  font-weight: 100;
  letter-spacing: 0.01em;
  font-size: 17px;
  box-sizing: border-box;
  padding: 10px 15px;
  display: block;
  position: absolute;
  margin-top: -40px;
  z-index: 2;
  pointer-events: none;
}
form .question input[type="text"] {
  appearance: none;
  background-color: none;
  border: 1px solid #6f4f4f;
  line-height: 0;
  font-size: 17px;
  width: 100%;
  display: block;
  box-sizing: border-box;
  padding: 10px 15px;
  border-radius: 60px;
  color: #6f4f4f;
  font-weight: 100;
  letter-spacing: 0.01em;
  position: relative;
  z-index: 1;
}
form .question input[type="text"]:focus {
  outline: none;
  background: #6f6f6f;
  color: white;
  margin-top: 30px;
}
form .question input[type="text"]:valid {
  margin-top: 30px;
}
form .question input[type="text"]:focus ~ label {
  -moz-transform: translate(0, -35px);
  -ms-transform: translate(0, -35px);
  -webkit-transform: translate(0, -35px);
  transform: translate(0, -35px);
}
form .question input[type="text"]:valid ~ label {
  text-transform: uppercase;
  font-style: italic;
  -moz-transform: translate(5px, -35px) scale(0.6);
  -ms-transform: translate(5px, -35px) scale(0.6);
  -webkit-transform: translate(5px, -35px) scale(0.6);
  transform: translate(5px, -35px) scale(0.6);
}
form .question input[type="password"] {
  appearance: none;
  background-color: none;
  border: 1px solid #6f4f4f;
  line-height: 0;
  font-size: 17px;
  width: 100%;
  display: block;
  box-sizing: border-box;
  padding: 10px 15px;
  border-radius: 60px;
  color: #6f4f4f;
  font-weight: 100;
  letter-spacing: 0.01em;
  position: relative;
  z-index: 1;
}
form .question input[type="password"]:focus {
  outline: none;
  background: #6f6f6f;
  color: white;
  margin-top: 30px;
}
form .question input[type="password"]:valid {
  margin-top: 30px;
}
form .question input[type="password"]:focus ~ label {
  -moz-transform: translate(0, -35px);
  -ms-transform: translate(0, -35px);
  -webkit-transform: translate(0, -35px);
  transform: translate(0, -35px);
}
form .question input[type="password"]:valid ~ label {
  text-transform: uppercase;
  font-style: italic;
  -moz-transform: translate(5px, -35px) scale(0.6);
  -ms-transform: translate(5px, -35px) scale(0.6);
  -webkit-transform: translate(5px, -35px) scale(0.6);
  transform: translate(5px, -35px) scale(0.6);
}

select {
  margin: 50px;
  width: 250px;
  padding: 5px 35px 5px 5px;
  font-size: 16px;
  border: 1px solid #ccc;
  height: 34px;
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
  background: url(food.ico) 96% / 15% no-repeat #eee;
}

/* CAUTION: IE hackery ahead */
select::-ms-expand { 
    display: none; /* remove default arrow on ie10 and ie11 */
}

/* target Internet Explorer 9 to undo the custom arrow */
@media screen and (min-width:0\0) {
    select {
        background:none\9;
        padding: 5px\9;
    } 
}

#id_feedback {
    width: 100%;
    height: 150px;
    padding: 12px 20px;
    box-sizing: border-box;
    border: 2px solid ##6f4f4f;
    border-radius: 4px;
    background-color: #f8f8f8;
    font-size: 16px;
    resize: none;
}
</style>

</head>
<body>
<script>
function as(){
 var my_time = new Date()
      alert("query submitted successfully at " + my_time);
    }
</script>
	<table align="center" width="100%" bgcolor="#343a40">
		<tr>
			<th>
				<div style="background-color:#343a40;width:100%;" align="right"><div style="width:10%;"><img src="{% static 'images/iiit.png'%}" height="100" width="100" alt="no image"></div>
			</th>
			<th>
				<p><font color="#ffffff" size="5">Indian institute of Information Technology , Sri city , Chittoor</font></p><font color="#fffff" size=4>(An Institute of National Importance under Act of Parliament)</p></font>
			</th>
		</tr>
	</table><center>
<div style="background-color:#007bff" >
  <div class="dropdown">
    <button class="button" style="vertical-align:middle" onclick="window.location.href='/mess/'">
      <span>HOME </span></button>
  </div>
<div class="dropdown">
    <button class="button" style="vertical-align:middle">
      <span>HOSTEL </span></button>
      <div class="dropdown-content">
        <a href="/hostel/roomregistration">ROOM REGISTRATION</a>
        <a href="/hostel/inout">HOSTEL LEAVE</a>
        <a href="/hostel/hostel_complaint">HOSTEL COMPLAINT</a>
        <a href="/hostel/guestEntry">GUESTS ENTRY</a>
      </div>
  </div>
  <div class="dropdown">
    <button class="button" style="vertical-align:middle">
      <span>MESS </span></button>
      <div class="dropdown-content">
        <a href="/mess/messmenu">MESS MENU</a>
        <a href="#">MESS COMPLAINT</a>
       
        <a href="/mess/refund">MESS REFUND</a>
      </div>
   </div>
	<button class="button" style="vertical-align:middle" onclick="window.location.href='file:///C:/Users/dell/Desktop/ASE-WEBPAGE/Login.html#'"><span>LOGOUT </span></button></center>
</div>
<table>
<tr>
  <td width="30%" valign="top">
<div class="img-rounded" style="float: left; background-color: #ffc107; width: 300px; height: 500px; border: 1px solid black; margin: 10px;"><h3 style="color: #ffffff; background-color: #28a745; text-align: center; margin: 0px; padding: 0px;">Announcements</h3><div id="cc-homepage-announcements" style="height: 320px; overflow-x: hidden; overflow-y: auto; padding: 6px; text-align: left;"><font color="red"><marquee direction="up">LIFT WILL BE INSTALLED WITHIN TWO WEEKS<BR><BR>TODAY, PUNUGULU WILL BE SERVED INSTEAD OF IDLY<br><br><br><br><br><br><br><br><br><br></marquee></font></BR></div>
</div>
  </td>
  <td width="63.5%" valign="top">
	{% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

  <div class="card">
  <center><p style="color:#B22222;font-size:35px;font-family:Copperplate Gothic Bold">MESS COMPLAINT</p></center></div>
 <div class="card">
 <form method="post" enctype="multipart/form-data" onSubmit="as()">
	{% csrf_token %}
{% include 'Mess/form_template.html' %}
 
<fieldset>
<br>
 <button type="submit">Submit</button></div>
</form>
</td>
</tr>
</table>
</body>

</html>

Mess/templates/Mess/form_template.html
{% for field in form %}
    <div>
        <div >
            <span ><font style='color:red'>{{ field.errors }}</font></span>
        </div>
        <label >{{ field.label_tag }}</label>
        <div >{{ field }}</div>
    </div>
{% endfor %}

Mess/templates/Mess/home.html
<!DOCTYPE html>
<html>
<head>
<style>
.button {
    background-color: #4CAF50;
    border: none;
    color: white;
    padding: 20px 70px;
    text-align: center;
    font-size: 18px;
    cursor: pointer;
}

.button:hover {
    background-color: green;
}
</style>
<style>
.dropbtn {
    background-color: #4CAF50;
    color: white;
    padding: 20px 50px;
    font-size: 18px;
    border: none;
}

.dropdown {
    position: relative;
    display: inline-block;
}

.dropdown-content {
    display: none;
    position: absolute;
    background-color: #f1f1f1;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
}

.dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
}

.dropdown-content a:hover {background-color: #ddd;}

.dropdown:hover .dropdown-content {display: block;}

.dropdown:hover .dropbtn {background-color: #3e8e41;}
</style>

</head>
<body>
  <table>
 <tr>
 <th> <img src="iiit.png" height="100" width="100" alt="Girl in a jacket"></th>
<th><h1><CENTER>INDIAN INSTITUTE OF INFORMATION TECHNOLOGY - SRICITY</h1></th>
</tr>
</table>
<center>
  <button class="button"><a href="https://www.w3schools.com">HOME</a></button>
  <div class="dropdown">
    <button class="dropbtn">HOSTEL</button>
    <div class="dropdown-content">
      <a href="#">COMPLAINT</a>
      <a href="#">GUEST ENTRY</a>
      <a href="#">ROOM REGISTRATION</a>
      <a href="#">HOSTEL LEAVE APPLICATION</a>
    </div>
  </div>
  <div class="dropdown">
    <button class="dropbtn">MESS</button>
    <div class="dropdown-content">
      <a href="#">MESS-MENU</a>
      <a href="#">MESS FEEDBACK</a>
      <a href="#">APPLY REFUND</a>
    </div>
  </div>
 
  <button class="button"><a href="https://www.w3schools.com">LOGOUT</a></button>
</center>

<div class="img-rounded" style="float: left; background-color: #e3f1ff; width: 360px; height: 420px; border: 1px solid black; margin: 10px;"><h3 style="color: #ffffff; background-color: #15317E; text-align: center; margin: 0px; padding: 0px;">Announcements</h3><div id="cc-homepage-announcements" style="height: 320px; overflow-x: hidden; overflow-y: auto; padding: 6px; text-align: left;">&nbsp;</div>
</div>

</body>
</html>

Mess/templates/Mess/login.html
<a href=" https://serene-wildwood-35121.herokuapp.com/login/5bdb4393203ce300150cb538">Login </a>
           

Mess/templates/Mess/loginsuccess.html
logged in as {{email}}